name: Starting the server

run-name: Starting the server

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
      PORT: 5000

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Start the server
        run: npm start
        working-directory: ./backend
